version: "3.8"
services: 
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=nicolas
      - MARIADB_PASSWORD=nicolas-mdp
      - MARIADB_DATABASE=applifirst
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - dev

  webservice:
    build: ./webservice
    container_name: webservice
    restart: always
    depends_on:
      db: 
        condition: service_healthy
    volumes: 
      - app_sources:/appli
    environment:
      - HOST=db
      - USER=nicolas
      - PASS=nicolas-mdp
      - NAME=applifirst
    networks: 
        - dev

  php_fpm: 
    build: ./php_fpm
    ports:
      - "9000:9000"
    # It is important that both containers can reference the same files
    volumes:
      - app_sources:/usr/share/nginx/html
    depends_on:
      - webservice
    networks:
      - dev

  nginx: 
    build: ./nginx
    volumes:
      - app_sources:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - php_fpm
    networks:
      - dev
      
networks: 
    dev:

volumes: 
    app_sources: